function [out] = plot_arrows(source, target, varargin)
    out = quiver3(  source(:, 1), source(:, 2), source(:, 3), ...
                    target(:, 1), target(:, 2), target(:, 3), ...
                    'MarkerFaceColor', 'r',  'Color', 'r', ...
                    varargin{:});
end
